name: Executar Testes Cypress

on:  
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  cypress-run:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  

      - name: Instalar Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install  

      - name: Executar testes Cypress
        run: |
          npx cypress run --reporter mocha
          
      - name: Criar diretório para relatórios
        run: mkdir -p mochareports

      - name: Mover relatórios para diretório específico
        run: mv cypress/reports/* mochareports/

      - name: Upload dos relatórios como artefatos
        uses: actions/upload-artifact@v4
        with:
          name: mocha-reports
          path: mochareports/
  
      - name: Upload dos vídeos de execução
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
